import {EditorView,basicSetup} from 'codemirror';
import {EditorState,Compartment} from '@codemirror/state';
import {keymap} from '@codemirror/view';
import {oneDark} from '@codemirror/theme-one-dark';
import {javascript} from '@codemirror/lang-javascript';
import {python} from '@codemirror/lang-python';
import {json} from '@codemirror/lang-json';
import {html} from '@codemirror/lang-html';
import {css} from '@codemirror/lang-css';
import {setDiagnostics} from '@codemirror/lint';
import {analyze,applyFixes,samples} from './analyzer.js';
const languageCompartment=new Compartment();
const $=s=>document.querySelector(s);let lang='javascript';let issues=[];let checked=false;
const modes={javascript:()=>javascript(),typescript:()=>javascript({typescript:true}),jsx:()=>javascript({jsx:true}),tsx:()=>javascript({jsx:true,typescript:true}),python,json,html,css};
const extensions={javascript:'js',typescript:'ts',jsx:'jsx',tsx:'tsx',python:'py',json:'json',html:'html',css:'css'};
const editor=new EditorView({state:EditorState.create({doc:samples.javascript,extensions:[basicSetup,oneDark,languageCompartment.of(modes[lang]()),EditorView.theme({'&':{backgroundColor:'#17191c'},'.cm-gutters':{backgroundColor:'#17191c'}}),EditorView.contentAttributes.of({'aria-label':'Code editor',spellcheck:'false'}),keymap.of([{key:'Mod-Enter',run:()=>{runCheck();return true;}}]),EditorView.updateListener.of(u=>{if(u.docChanged){checked=false;issues=[];$('#insight-status').textContent='Edited';}const line=u.state.doc.lineAt(u.state.selection.main.head);$('#cursor').textContent=`Ln ${line.number}, Col ${u.state.selection.main.head-line.from+1}`;$('#line-count').textContent=`${u.state.doc.lines} lines`;})]}),parent:$('#editor')});
function runCheck(){issues=analyze(editor.state.doc.toString(),lang);checked=true;$('#insight-status').textContent=issues.length?`${issues.length} found`:'Checked';$('#results').innerHTML='<div class="success-icon">✓</div><h2>Checks complete.</h2><p>'+ (issues.length?`${issues.length} items need your attention. Detailed fixes are being prepared.`:'No syntax errors found.')+'</p>';}
$('#analyze').onclick=runCheck;$('#language').onchange=e=>{lang=e.target.value;editor.dispatch({effects:languageCompartment.reconfigure(modes[lang]())});$('#filename').textContent=`playground.${extensions[lang]}`;$('#file-icon').textContent=extensions[lang].toUpperCase();};$('#sample').onclick=()=>{editor.dispatch({changes:{from:0,to:editor.state.doc.length,insert:samples[lang]}});runCheck();};
// Diagnostic actions always operate on the current editor document.
let pendingCode=null;let pendingOriginal=null;let previousCode=null;let toastTimer;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),2600);}
const scope=()=>lang==='python'?'Python grammar checks; no runtime or import validation.':(['typescript','tsx'].includes(lang)?'Syntax and selected common mistakes; project-wide type checking is not included.':'Syntax and selected common mistakes; runtime behavior is not checked.');
function renderResults(){
 const code=editor.state.doc.toString();const errors=issues.filter(i=>i.severity==='error').length;const fixable=issues.filter(i=>i.replacement!==undefined).length;
 const panel=$('#results');panel.classList.add('has-results');
 if(!code.trim()){panel.innerHTML='<div class="empty-icon">⌕</div><h2>Your workspace is empty.</h2><p>Paste some code or load an example to get started.</p>';return;}
 panel.innerHTML=issues.length?`<div class="result-summary"><span class="error-count">${errors} error${errors===1?'':'s'} <span style="color:#656d70">/</span> ${issues.length-errors} suggestion${issues.length-errors===1?'':'s'}</span><span style="color:#88917e;font-size:11px">${fixable} fixable</span></div>${issues.map((i,k)=>`<div class="issue ${i.severity}" tabindex="0" role="button" data-issue="${k}" aria-label="Go to line ${i.line}: ${esc(i.title)}"><div class="issue-top"><span>${i.severity==='error'?'⊗ ERROR':'◇ SUGGESTION'}</span><span>LINE ${i.line} ↗</span></div><h3>${esc(i.title)}</h3><p>${esc(i.detail)}</p></div>`).join('')}`:`<div class="success-icon">✓</div><h2>No issues detected.</h2><p>Your snippet passes the available checks. You’re ready to keep building.</p>`;
 panel.innerHTML+=`<div class="result-actions">${fixable?'<button class="primary" id="review-fixes">Review fixes <span>↗</span></button>':''}<button class="secondary" id="copy-code">Copy code</button>${lang!=='python'?'<button class="secondary" id="format-code">Format</button>':''}${previousCode!==null?'<button class="secondary" id="undo-fix">Undo last change</button>':''}</div><p class="scope-note">${scope()}</p>`;
 panel.querySelectorAll('[data-issue]').forEach(el=>{const go=()=>{const i=issues[Number(el.dataset.issue)];editor.dispatch({selection:{anchor:i.from},scrollIntoView:true});editor.focus();};el.onclick=go;el.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();go();}};});
 $('#review-fixes')?.addEventListener('click',()=>showReview(applyFixes(editor.state.doc.toString(),issues),`${fixable} suggested correction${fixable===1?'':'s'}. Review the result before applying.`));
 $('#copy-code')?.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(editor.state.doc.toString());toast('Code copied to clipboard');}catch{toast('Clipboard unavailable. Select the code and copy it manually.');}});
 $('#format-code')?.addEventListener('click',formatCode);
 $('#undo-fix')?.addEventListener('click',()=>{const code=previousCode;previousCode=null;replaceCode(code);performCheck();toast('Last change undone');});
}
function performCheck(){try{issues=analyze(editor.state.doc.toString(),lang);checked=true;$('#insight-status').textContent=issues.length?`${issues.length} found`:'Checked';editor.dispatch(setDiagnostics(editor.state,issues.map(i=>({from:i.from,to:i.to,severity:i.severity,message:i.title}))));renderResults();return issues;}catch(error){$('#insight-status').textContent='Check failed';$('#results').textContent='Could not check this snippet. Try a smaller snippet and check again.';toast(error.message);return [];}}
runCheck=performCheck;
function replaceCode(code){editor.dispatch({changes:{from:0,to:editor.state.doc.length,insert:code}});}
function showReview(code,description){pendingCode=code;pendingOriginal=editor.state.doc.toString();$('#original').textContent=pendingOriginal;$('#corrected').textContent=code;$('#review-description').textContent=description;$('#review').showModal();}
async function formatCode(){const before=editor.state.doc.toString();const beforeLang=lang;const button=$('#format-code');button.disabled=true;button.textContent='Formatting…';try{const [prettier,babel,estree,typescript,htmlPlugin,postcss]=await Promise.all([import('prettier/standalone'),import('prettier/plugins/babel'),import('prettier/plugins/estree'),import('prettier/plugins/typescript'),import('prettier/plugins/html'),import('prettier/plugins/postcss')]);const result=await prettier.format(before,{parser:{javascript:'babel',jsx:'babel',typescript:'typescript',tsx:'typescript',json:'json',html:'html',css:'css'}[lang],plugins:[babel,estree,typescript,htmlPlugin,postcss],tabWidth:2});if(before!==editor.state.doc.toString()||beforeLang!==lang){toast('Code changed. Format again to use the latest version.');return;}if(result===before)toast('Your formatting is already consistent');else showReview(result,'Consistent spacing and indentation. Review the formatted code.');}catch(e){toast('Fix the syntax errors before formatting.');}finally{button.disabled=false;button.textContent='Format';}}
$('#analyze').onclick=performCheck;
$('#sample').onclick=()=>{previousCode=editor.state.doc.toString();replaceCode(samples[lang]);performCheck();toast('Example loaded');};
$('#language').onchange=e=>{lang=e.target.value;editor.dispatch({effects:languageCompartment.reconfigure(modes[lang]())});$('#filename').textContent=`playground.${extensions[lang]}`;$('#file-icon').textContent=extensions[lang].toUpperCase();performCheck();};
$('#apply').onclick=()=>{if(pendingOriginal!==editor.state.doc.toString()){toast('Code changed. Check it again before applying fixes.');$('#review').close();return;}previousCode=pendingOriginal;replaceCode(pendingCode);$('#review').close();performCheck();toast('Changes applied');};
$('#cancel-review').onclick=$('#close-review').onclick=()=>$('#review').close();
$('#review').addEventListener('click',e=>{if(e.target===$('#review')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close();}});
let refreshTimer;editor.dispatch({effects:StateListener()});
function StateListener(){return StateEffectAppend(EditorView.updateListener.of(u=>{if(u.docChanged){clearTimeout(refreshTimer);$('#insight-status').textContent='Edited';$('#results').classList.remove('has-results');$('#results').innerHTML='<div class="empty-icon">⌕</div><h2>Ready for another look.</h2><p>Your code has changed. Check it again to see up-to-date insights.</p>';refreshTimer=setTimeout(()=>{if(!checked)editor.dispatch(setDiagnostics(editor.state,[]));},0);}}));}
function StateEffectAppend(extension){return EditorStateEffects.appendConfig.of(extension);}
import {StateEffect as EditorStateEffects} from '@codemirror/state';
$('#line-count').textContent=`${editor.state.doc.lines} lines`;
if(document.modelContext?.registerTool){const tool={name:'check_code',description:'Replace the visible editor code and check syntax in the specified language. Returns diagnostics; does not execute code.',inputSchema:{type:'object',properties:{code:{type:'string'},language:{type:'string',enum:Object.keys(modes)}},required:['code','language'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute(input){if(!input||typeof input.code!=='string'||!Object.hasOwn(modes,input.language))throw new Error('Provide code and a supported language.');if(input.code.length>100000)throw new Error('Use snippets under 100,000 characters.');lang=input.language;$('#language').value=lang;editor.dispatch({effects:languageCompartment.reconfigure(modes[lang]())});$('#filename').textContent=`playground.${extensions[lang]}`;$('#file-icon').textContent=extensions[lang].toUpperCase();replaceCode(input.code);return {language:lang,issues:performCheck().map(({line,title,severity})=>({line,title,severity}))};}};try{Promise.resolve(document.modelContext.registerTool(tool)).catch(()=>{});}catch{}}
